quarkus.datasource.db-kind = postgresql
quarkus.datasource.username = topicos1
quarkus.datasource.password = 123456
quarkus.datasource.jdbc.url = jdbc:postgresql://localhost:5432/topicos1db
quarkus.devservices.enabled=false

quarkus.hibernate-orm.database.generation=drop-and-create

quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.log.bind-parameters=true
quarkus.oidc.enabled=true
quarkus.oidc.application-type=service
quarkus.oidc.auth-server-url=http://localhost:8180/realms/newsvi
quarkus.oidc.client-id=newsvi-api
quarkus.oidc.credentials.secret=YOUR_CLIENT_SECRET
quarkus.oidc.token.audience=newsvi-api
quarkus.oidc.roles.source=accesstoken
quarkus.oidc.authentication.user-info-required=false
quarkus.oidc.authentication.scopes=openid,email,profile
quarkus.oidc.authentication.redirect-path=/user
quarkus.oidc.authentication.restore-path-after-redirect=true
quarkus.http.auth.permission.authenticated.paths=/usuarios/*,/pedidos/*,/desejos/*
quarkus.http.auth.permission.authenticated.policy=authenticated

