@startuml diagrama
title Diagrama de Classes - CRUD's Administrativos
caption Aluno: Bernardo dos Santos Graça

' --------------------
' Classes principais
' --------------------

class Filme {
    - nome : String
    - duracao : String
    - sinopse : String
    - idiomaOriginal : String 
    - anoLancamento : Integer
}



enum TipoSessao {
    DUBLADA
    LEGENDADA
}

enum ClassificacaoIndicativa {
    LIVRE
    DEZ
    DOZE
    QUATORZE
    DEZESSEIS
    DEZOITO
}

class Premio {
    - nome : String
    - categoria : String
    - ano : Integer
}

class Genero {
    - nome : String
}


class Ator {
    - nome : String
}



class Sessao {
    - horarioInicio : DateTime
    - horarioFim : DateTime

}

class Sala {
}

class Poltrona {
    - nome : String
    - estaOcupada : Boolean
}


' --------------------
' Subclasses
' --------------------
class AtorPremiado {

}

class FilmePremiado {

}




' --------------------
' Herança
' --------------------

AtorPremiado --|> Ator
FilmePremiado --|> Filme

' --------------------
' Relacionamentos
' --------------------
Filme "*" --> "*" Ator : atoresPrincipais
Filme "*" --> "*" Genero : genero
FilmePremiado "*" --> "*" Premio : premiacao
AtorPremiado "*" --> "*" Premio : premiacao
Sessao "*" --> "1" TipoSessao : tipoSessao
Sessao "*" --> "*" Sala : salas
Sala "1" *--> "*" Poltrona : poltronas
Sessao "*" o--> "1" Filme : filme
Filme "*" --> "1" ClassificacaoIndicativa : classificacaoIndicativa
@enduml